# Generated by Django 4.0.4 on 2022-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_sub',
            field=models.DateTimeField(),
        ),
    ]
