# Generated by Django 4.0.4 on 2022-04-14 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_exp_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='color',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='Intro',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.DO_NOTHING, to='core.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
