# Generated by Django 4.0.4 on 2022-04-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_song_album_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
