# Generated by Django 4.0.4 on 2022-04-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_album_artist_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
