# Generated by Django 4.0.4 on 2022-04-19 17:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_song_album_remove_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='core.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='core.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
