# Generated by Django 4.0.4 on 2022-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_song_album_song_artist_alter_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_slug',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_slug',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='pl_slug',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='pls_slug',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
