# Generated by Django 4.0.4 on 2022-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_album_album_slug_remove_artist_artist_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.CharField(choices=[('pop', 'Pop'), ('rap', 'Rap'), ('rock', 'Rock'), ('disslove', 'DissLove'), ('rb', 'R&B'), ('jazz', 'Jazz'), ('electronica', 'Electronica'), ('religious', 'Religious'), ('instrumental', 'Instrumental')], default='pop', max_length=20),
        ),
    ]
