# Generated by Django 4.0.4 on 2022-04-22 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_artist_bio_remove_artist_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_sub',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 21, 2, 9, 229748)),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.DO_NOTHING, to='core.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
