# Generated by Django 4.0.4 on 2022-04-22 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_exp_sub_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_sub',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 22, 59, 45, 562208)),
        ),
        migrations.CreateModel(
            name='PlaylistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.DO_NOTHING, to='core.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
