# Generated by Django 3.2.13 on 2022-05-23 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_artist_tags_artist_tags_remove_song_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_sub',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 17, 25, 13, 192638)),
        ),
    ]
